export enum Material {
  WOOD = 'wood',
  STEEL = 'steel',
  ALUMINUM = 'aluminum',
  IRON = 'iron',
  BRASS = 'brass',
  COPPER = 'copper',
  PLASTIC = 'plastic',
  GLASS = 'glass',
  CERAMIC = 'ceramic',
  CLOTH = 'cloth',
  LEATHER = 'leather',
  RATTAN = 'rattan',
  FOAM = 'foam',
  VINYL = 'vinyl',
  OTHER = 'other',
}
